### PR TITLE
Add Sandboxed IFrame widget and command

### PR DESCRIPTION
**Pull request by canavandl**
Add Sandboxed IFrame widget and command
* [x] Add ILayoutRestorer functionality
* [ ] Add model css to increase visible input width (will have to reimplement ``showDialog`` to access className ?)
* [ ] Write better copy for modal
* [ ] Make panel title be "Web Page: [url]" or just "[url]"

Questions?
* [ ] Why isn't the Sandbox panel added as the top tab and "selected" via CSS ?!?
* [ ] Error handling for bad urls or security errors (ie CORS)? Throw error in modal?

### CODE REVIEW

**Comment by canavandl** [comment]
Current status:

Command in palette
screen shot 2018-01-19 at 11 56 22 pm


Modal
screen shot 2018-01-19 at 11 56 36 pm


Embedded content
screen shot 2018-01-19 at 11 56 52 pm

**Comment by skliarpawlo** [comment]
Hi @canavandl thanks for this PR, for some reason only example site bokeh.com works for me, for any other pages including google.com shows blank page, any ideas why this is so?

Also a small nice-to-have would be saving links to specific sites in Launcher to avoid the need to type urls each time.

Thanks!

**Comment by canavandl** [comment]
Will open follow-up issues to resolve unaddressed deficiencies.

**Comment by canavandl** [comment]
@skliarpawlo - google.com won't load because google.com disallows iframe-ing their content (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options), in order to prevent click-jacking attacks. Hopefully I'll be able to notify the user of this in the future.

**Pull request merged**
